services:
    java:
        build: ./java
        volumes:
            - ./output:/output
    go:
        build: ./go
        volumes:
            - ./output:/output
    ruby:
        build: ./ruby
        volumes:
            - ./output:/output
            - ./ruby:/app
    csharp:
        build: ./csharp
        volumes:
            - ./output:/output

    javascript:
            build: ./javascript
            volumes:
                - ./output:/output

    python:
        build: ./python
        volumes:
            - ./output:/output
            - ./python:/app
